:toc: macro
:stern: https://github.com/wercker/stern[Stern]
:kubectx: https://github.com/ahmetb/kubectx[Kubectx & Kubens]
:kubectl-tree: https://awesomeopensource.com/project/ahmetb/kubectl-tree[kubectl-tree]
:proxyman: https://proxyman.io[Proxyman]
:fzf: https://github.com/junegunn/fzf[fzf]
:silverSearcher: https://github.com/ggreer/the_silver_searcher[the silver searcher]
:how2: https://github.com/santinic/how2[how2]
:navi: https://github.com/denisidoro/navi[navi]
:forgit: https://github.com/wfxr/forgit[forgit]
:exa: https://github.com/ogham/exa[exa]
:bat: https://github.com/sharkdp/bat[bat]
:htop: https://github.com/hishamhm/htop[htop]
:autoenv: https://github.com/inishchith/autoenv[autoenv]
:thefuck: https://github.com/nvbn/thefuck[thefuck]
:netshoot: https://github.com/nicolaka/netshoot[netshoot]
:sourcetree: https://www.sourcetreeapp.com[Sourcetree]
:omnifocus: https://www.omnigroup.com/omnifocus[OmniFocus]
:omnigraffle: https://www.omnigroup.com/omnigraffle[OmniGraffle]
:marginnote: https://www.marginnote.com[MarginNote]
:mosaic: https://www.lightpillar.com/mosaic.html[Mosaic]
:apptivate: http://apptivateapp.com[Apptivate]
:enpass: https://www.enpass.io[Enpass]
:magnet: https://magnet.crowdcafe.com[Magnet]
:trickster: https://www.apparentsoft.com/trickster[Trickster]
:hazeover: https://hazeover.com[HazeOver]

= link:README.adoc[Home]

The list of tools that every developer should have installed.

---

toc::[]

---

== Shell

{fzf}::
Command line fuzzy finder allows to select the command ending interactively.

{silverSearcher}::
Very fast an powerful file search tool.

{how2}::
Search for commands directy from the command line.

{navi}::
Personalised history of easily querable commands.

{forgit}::
Easily use git from the command line. Features fzf.

{exa}::
Modern replacement for ls.

{bat}::
Modern replacement for cat.

{htop}::
Modern replacement for htop.

{thefuck}::
Corrects the last ill-entered command.

== Kubernetes

=== Tools

{stern}::
Kubernetes utility to easily see colored logs from multiple containers.

{kubectx}::
Small utility to switch through clusters and namespaces smoothly.

{kubectl-tree}::
Can present dependency trees of Kubernetes resources.

== MacOS

{omnifocus}::
Great task management software.

{omnigraffle}::
Leading charting software. Destroys anything you know.

{sourcetree}::
The best GIT repository manager.

{proxyman}::
A tool for sniffing the network traffic in a pleasant and MacOS-compliant way.

{marginnote}::
Cross-reference documents with annotations on a mindmap in a single application.

{mosaic}::
Best workspace window organizer out there.

{apptivate}::
Easily assign global shortcuts to your applications. Pressing a combination will bring the application forward instantly if opened or open if not present.

{enpass}::
Free but comprehensive and goregously designed password manager with actually working extensions for all major browsers including Safari.

{magnet}::
Extremelly simple, predictable and neat window manager.

{trickster}::
Keeps recently used items in the top bar icon with quick search capability.

{hazeover}::
Distraction dimmer that dimms inactive windows so you can focus on the active one. Great for people who overuse maximization to their own peril.

=== Tricks

Dim the icons of hidden applications in dock::
`defaults write com.apple.Dock showhidden -bool YES && killall Dock`

Enable highlight hover effect for the grid view of a stack (Dock)::
`defaults write com.apple.dock mouse-over-hilite-stack -bool true`

Set the icon size of Dock items to 36 pixels::
`defaults write com.apple.dock tilesize -int 36`

Change minimize/maximize window effect::
`defaults write com.apple.dock mineffect -string "scale"`

Minimize windows into their application’s icon::
`defaults write com.apple.dock minimize-to-application -bool true`

Enable spring loading for all Dock items::
`defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true`

Show indicator lights for open applications in the Dock::
`defaults write com.apple.dock show-process-indicators -bool true`

Show only open applications in the Dock::
`defaults write com.apple.dock static-only -bool true`

Don’t animate opening applications from the Dock::
`defaults write com.apple.dock launchanim -bool false`

Speed up Mission Control animations::
`defaults write com.apple.dock expose-animation-duration -float 0.1`

Disable Dashboard::
`defaults write com.apple.dashboard mcx-disabled -bool true`

Don’t show Dashboard as a Space::
`defaults write com.apple.dock dashboard-in-overlay -bool true`

Don’t automatically rearrange Spaces based on most recent use::
`defaults write com.apple.dock mru-spaces -bool false`

Remove the auto-hiding Dock delay::
`defaults write com.apple.dock autohide-delay -float 0`

Remove the animation when hiding/showing the Dock::
`defaults write com.apple.dock autohide-time-modifier -float 0`

Automatically hide and show the Dock::
`defaults write com.apple.dock autohide -bool true`

Make Dock icons of hidden applications translucent::
`defaults write com.apple.dock showhidden -bool true`

Don’t show recent applications in Dock::
`defaults write com.apple.dock show-recents -bool false`

== Docker

=== Useful containers

{netshoot}::
A swiss knife for network debugging.
