:toc: macro
:stern: https://github.com/wercker/stern[Stern]
:kubectx: https://github.com/ahmetb/kubectx[Kubectx & Kubens]
:kubectl-tree: https://awesomeopensource.com/project/ahmetb/kubectl-tree[kubectl-tree]
:proxyman: https://proxyman.io[Proxyman]
:fzf: https://github.com/junegunn/fzf[fzf]
:silverSearcher: https://github.com/ggreer/the_silver_searcher[the silver searcher]
:how2: https://github.com/santinic/how2[how2]
:navi: https://github.com/denisidoro/navi[navi]
:forgit: https://github.com/wfxr/forgit[forgit]
:exa: https://github.com/ogham/exa[exa]

= link:README.adoc[Home]

The list of tools that every developer should have installed.

---

toc::[]

---

== Shell

{fzf}::
Command line fuzzy finder allows to select the command ending interactively.

{silverSearcher}::
Very fast an powerful file search tool.

{how2}::
Search for commands directy from the command line.

{navi}::
Personalised history of easily querable commands.

{forgit}::
Easily use git from the command line. Features fzf.

{exa}::
Modern replacement for ls.

== Kubernetes

=== Tools

{stern}::
Kubernetes utility to easily see colored logs from multiple containers.

{kubectx}::
Small utility to switch through clusters and namespaces smoothly.

{kubectl-tree}::
Can present dependency trees of Kubernetes resources.

== MacOS

=== Networking

{proxyman}::
A tool for sniffing the network traffic in a pleasant and MacOS-compliant way.

=== Tricks

Dim the icons of hidden applications in dock::
`defaults write com.apple.Dock showhidden -bool YES && killall Dock`
